CREATE TABLE Person (
	[id] BIGINT NOT NULL IDENTITY,
	[ADDRESS] VARCHAR(100) NOT NULL,
	[first_name] VARCHAR(80) NOT NULL,
	[last_name] VARCHAR(80) NOT NULL,
	gender VARCHAR(6) NOT NULL,
	PRIMARY KEY([id])
)